### ISSUE TITLE
import fail

### ISSUE THREAD

**Issue by bransonngai** [xldistance/vnpy_bybit_v5#1]
hi, i got import error in

from vnpy.trader.utility import (save_connection_status,delete_dr_data,get_folder_path,load_json, save_json,remain_digit,get_symbol_mark,get_local_datetime,extract_vt_symbol,TZ_INFO,GetFilePath)
from vnpy.trader.setting import bybitone_account #导入账户字典

what is the custom object added? thank you.

**Comment by xldistance** [comment]
https://github.com/xldistance/vnpy_utility
